[package]
name = "rust_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
rclrs = "0.4.1"
anyhow = "1.0.98"
tokio = { version = "1.45.1", features = ["full"] }
nalgebra = "0.33.2"

## msgs
sensor_msgs = "4.2.3"
std_msgs = "4.2.3"
ackermann_msgs = "*" 
